#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.95
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   4

# Application Exceptions
yabai -m rule --add app="^iStat" manage=off
yabai -m rule --add app="^Bartender 4$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^TogglDesktop$" manage=off
yabai -m rule --add app="^Setapp$" manage=off sticky=on

# Firefox Exceptions
yabai -m rule --add app="^Firefox$" title="^Picture-in-Picture$" manage=off

echo "yabai configuration loaded.."
